### ISSUE TITLE
Need request

### ISSUE THREAD

**Issue by seifibrahim32** [Lakhankumawat/smart-home-app#12]
I'm in GSSoC'22 contributor , i did that before in the college the Flutter IoT and i may give you a copy of what i did ....
I am ready to contribute to this project and thats the project
https://youtu.be/-CX2kbgNCxA
I used microcontroller before and i used Firebase an Flutter.

**Comment by seifibrahim32** [comment]
i can*

**Comment by seifibrahim32** [comment]
If we are about to make IoT work we need ESP8266 but i hadnt digged too much just to knoe
my email : seifibrahim32@gmail.com so we may havr a medium to communicate.

**Comment by Lakhankumawat** [comment]
A mentor will review this pull request shortly , please have patience.

**Comment by seifibrahim32** [comment]
sure but when

**Comment by Lakhankumawat** [comment]
I am really sorry for late response actually i was busy with some other stuff these days . mail me your contact and i'll add you to mentors group kumawatlakhan07072001@gmail.com

**Comment by Lakhankumawat** [comment]
I am really sorry for late response actually i was busy with some other stuff these days , have you joined discord i will be having a weekly meet with mentors on voice channel please drop your primary mail i'll message your before meet so you can join on time and we can dicuss in a better way .

**Comment by seifibrahim32** [comment]
yeahhhh i amon the server

**Comment by seifibrahim32** [comment]
i joined but what is my task on this project to make Firebase??.

**Comment by Lakhankumawat** [comment]
You are familiar with IOT using flutter so we will be glad if you take that task , but expain us what you actually you'll be contributing dm me on discord and we will discuss out things in discord .

**Comment by seifibrahim32** [comment]
Ok for sure i will text you on Discord

**Comment by seifibrahim32** [comment]
I work on it...
