### ISSUE TITLE
Create a menu page 

### ISSUE THREAD

**Issue by ChetasShree** [Lakhankumawat/smart-home-app#13]
Hi 
I am a contributor at GSSOC'22 and I want to create the menu page in flutter , pls assign this issue to me

![Menu Page](https://user-images.githubusercontent.com/75165587/156103360-37a09a03-880f-42c0-87af-f3ab2c5901ac.PNG)

**Comment by Lakhankumawat** [comment]
A mentor will review this pull request shortly , please have patience.

**Comment by ChetasShree** [comment]
Can i start working on this page ? can this issue be assigned to me?

**Comment by Lakhankumawat** [comment]
Assigned to you make sure you follow code conventions and quality of code 🙃

**Comment by Chitrakshi2531** [comment]
Hey @Lakhankumawat I wanted to work on this issue, Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant.

**Comment by Lakhankumawat** [comment]
I would recommend the contributor of this issue to fetch upstream and resolve conflicts before creating a new Pull Request.

**Comment by Lakhankumawat** [comment]
hi @ChetasShree  you have 2 more days then this issue will be assigned to someone else

**Comment by Chitrakshi2531** [comment]
@Lakhankumawat this issue is still open, please assign it to me.

**Comment by Lakhankumawat** [comment]
Issue assigned to @Chitrakshi2531  due to overtime
