### ISSUE TITLE
Settings Option

### ISSUE THREAD

**Issue by pranjalkatiyar** [Lakhankumawat/smart-home-app#14]
Hi 
I love to work on the settings page, pls assign this to me
![image1](https://user-images.githubusercontent.com/76843696/156191993-85a495b4-1cbf-4454-9fef-02db5e8d4068.jpg)

**Comment by pranjalkatiyar** [comment]
can i work on this one?

**Comment by Lakhankumawat** [comment]
Assigned to you make sure you follow code conventions and quality of code 🙃

**Comment by Lakhankumawat** [comment]
I would recommend the contributor of this issue to fetch upstream and resolve conflicts before creating a new Pull Request.

**Comment by Lakhankumawat** [comment]
hi @pranjalkatiyar  you have 5 more days then this issue will be assigned to someone else

**Comment by pranjalkatiyar** [comment]
Oky i m working on it

**Comment by Lakhankumawat** [comment]
You are overtime with your issue , 1 more day and then it will be assigned to someone else .
