### ISSUE TITLE
Edit Profile Page

### ISSUE THREAD

**Issue by VrishtiGupta11** [Lakhankumawat/smart-home-app#19]
### Description

Hi, I would like to work on **Edit Profile Screen**. I will be making new screen over `smart-home-app/lib/src/screens/` directory.
Please assign me this task.
Below is the screen on which I want to work.
![Smart Home - Edit Profile](https://user-images.githubusercontent.com/53931644/156615416-bc8e3c08-c360-4b47-88fa-000075fb6917.png)

### Domain

UI/UX

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/smart-home-app/blob/master/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/smart-home-app/blob/master/.github/CODE_OF_CONDUCT.md) of Smart Home App.

**Comment by HarshKumarChoudary** [comment]
Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant

**Comment by Lakhankumawat** [comment]
I would recommend the contributor of this issue to fetch upstream and resolve conflicts before creating a new Pull Request.
