### ISSUE TITLE
Savings Page screen

### ISSUE THREAD

**Issue by Darshak11** [Lakhankumawat/smart-home-app#20]
The savings screen is not yet there, so I would like to implement it.Please assign me this task under the Gsssoc label.

**Comment by WarMac4964** [comment]
Please add all the details of the screen, 
1. What's going to be there on the screen
2. Add the design file in the issue description itself

**Comment by Lakhankumawat** [comment]
I would recommend the contributor of this issue to fetch upstream and resolve conflicts before creating a new Pull Request.

**Comment by Lakhankumawat** [comment]
![image](https://user-images.githubusercontent.com/55774240/158311952-82dedcf3-8245-49e3-b9c0-d3ea65983a43.png)

@Darshak11 you have 5 more days and then this issue will be assigned to someone else

**Comment by Chitrakshi2531** [comment]
I wanted to work on this issue, please /assign me the task.
