### ISSUE TITLE
schedule in  lightening screen widget overflow

### ISSUE THREAD

**Issue by mariam199911** [Lakhankumawat/smart-home-app#29]
### Description

I would like start my work by fixing this bug. Please assign me.

Weather

Child widgets inside weather widget gets overflowed by 20 pixels on the bottom.

### Domain

Other

### Type of Contribution

Bug Fixing

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/smart-home-app/blob/master/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/smart-home-app/blob/master/.github/CODE_OF_CONDUCT.md) of Smart Home App.

**Comment by Lakhankumawat** [comment]
Weather & Energy widget overflow #24 already assigned

**Comment by mariam199911** [comment]
my issue is about schedule in lightening screen widget overflow but i but wrong description sorry for that\
