### ISSUE TITLE
Favourites screen

### ISSUE THREAD

**Issue by HetviSoni** [Lakhankumawat/smart-home-app#32]
### Description

Hey , I would like to work upon creating the "Favourites Screen" as below . Please assign me this issue under GSSoc.
![Screenshot (194)](https://user-images.githubusercontent.com/76479104/157494183-6b46e009-485d-45d9-90e5-c7ff97b59dfe.png)

### Domain

UI/UX

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/smart-home-app/blob/master/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/smart-home-app/blob/master/.github/CODE_OF_CONDUCT.md) of Smart Home App.

**Comment by chandan0000** [comment]
LGMT

**Comment by Lakhankumawat** [comment]
hi @HetviSoni  the PR related to this issue is not created or this issue is inactive for long time , if such case remains after 10 days this issue will be assignend to someone else

**Comment by jaydeore-007** [comment]
Hey, I would like to work on this issue, can please assign it to me?

**Comment by Lakhankumawat** [comment]
> Hey, I would like to work on this issue, can please assign it to me?

It will be assigned to you after 5 days.

**Comment by Lakhankumawat** [comment]
Issue assigned to @jaydeore-007

**Comment by HetviSoni** [comment]
Hey, I apologize for being too late. But I have completed working on this issue. Can I get reassigned this issue so that I can create a pr?
