### ISSUE TITLE
💬 FAQ Page

### ISSUE THREAD

**Issue by Lakhankumawat** [Lakhankumawat/smart-home-app#5]
Challanges
- Creating FAQ Page for the app following the original design pattern
- Creating Static FAQ Dropdown with relevant answers
- Design UI/UX for page
- Navigation of user from FAQ to particular page (if necessay )

**Comment by Ashish-AI** [comment]
Hi @Lakhankumawat, would like to take this up.

**Comment by Lakhankumawat** [comment]
You will be accompanied by some mentor shortly

**Comment by Lakhankumawat** [comment]
![image](https://user-images.githubusercontent.com/55774240/155352164-dd47e4dd-fe08-4cdf-ba0d-7cc5519be473.png)
Go thorugh Figma Files to check it out and get assets for the same :

**Comment by Lakhankumawat** [comment]
Challanges : 
- List Must be collapsable and must consists of inner elements as shown in image above 
- Design Constrains must be followed i.e. your design must be responsive
- Add Navigation and routing
- maintain code quality and make separate components and reusable widgets .

**Comment by Ashish-AI** [comment]
@Lakhankumawat where can I find the figma link?

**Comment by Lakhankumawat** [comment]
Repo README at the top

**Comment by Ashish-AI** [comment]
cool, was curious to know if a PR raised now will be counted in GSSOC?

**Comment by Lakhankumawat** [comment]
Just wait for some time because the mentors are not yet assigned , also if you wish to contribute I'll make sure you get your points when it starts .

**Comment by Lakhankumawat** [comment]
yaa

**Comment by Subhajitongit** [comment]
Hey @Lakhankumawat I wanted to work on this issue, so could you assign me the task.

**Comment by nrd26** [comment]
Hi, 
Please let me know if I can work on this task

**Comment by Darshak11** [comment]
Can I get assigned this thing?

**Comment by RanchoDbest** [comment]
@chandan0000 @WarMac4964  Can you please assign this task to me ?

**Comment by Lakhankumawat** [comment]
Assigned to @Subhajitongit  because he came second and @Ashish-AI  is already assigned an issue  and we follow first come first serve principle  make sure you follow code conventions and quality of code 🙃

**Comment by Lakhankumawat** [comment]
nd sorry to other guys who did n't get the issue menwhile you guys can explore figma designs and come up with something new or you can suggest something new by creating a new issue and describing it in detail and we will be happy to see it .

**Comment by Lakhankumawat** [comment]
I would recommend the contributor of this issue to fetch upstream and resolve conflicts before creating a new Pull Request.

**Comment by Lakhankumawat** [comment]
hi @Subhajitongit  you have 4 more days then this issue will be assigned to someone else

**Comment by Lakhankumawat** [comment]
Un assigning @Subhajitongit due to inactivity

**Comment by Lakhankumawat** [comment]
@MnCSSJ4x since you were next in queue who hasn't assigned any issues so  this issue is assigned to you , you can start working on it .

**Comment by anushkashelke** [comment]
Can you assign this task to me?
