### ISSUE TITLE
Signup UI

### ISSUE THREAD

**Issue by RanchoDbest** [Lakhankumawat/smart-home-app#56]
### Description

There is no Figma File for signup page. 

### Domain

UI/UX

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/smart-home-app/blob/master/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/smart-home-app/blob/master/.github/CODE_OF_CONDUCT.md) of Smart Home App.

**Comment by RanchoDbest** [comment]
@Lakhankumawat Can you please assign this task to me ? I will create UI according to Login Screen or update Figma file.

**Comment by Lakhankumawat** [comment]
you don't have access to update figma file , instead you create your design in a new figma file show me design and i will accept it if it LGTM

**Comment by Lakhankumawat** [comment]
any updates ?

**Comment by ishashukla183** [comment]
I would like to work on this issue

**Comment by anushkashelke** [comment]
Hey I am a flutter developer, I would like to contribute on this issue .
