### ISSUE TITLE
ℹ️About Page

### ISSUE THREAD

**Issue by Lakhankumawat** [Lakhankumawat/smart-home-app#6]
Challanges
- About App / App Design / App Architechture
- App Idea and Application
- App Source Code Link
- About Page for developers 
- Must include about developers link to github profile opening in browser

**Comment by nrd26** [comment]
Hi @Lakhankumawat ,
If this issue is still available to work on, I would love to work on it

**Comment by Subhajitongit** [comment]
Hey @Lakhankumawat ,
I want to work on this issue, am a GSSoC'22 participant, could you please assign me the task.

**Comment by Darshak11** [comment]
Can i get this task assigned ?

**Comment by Lakhankumawat** [comment]
@nrd26  this issue is assigned to you , you can start working on it thanks .

**Comment by Lakhankumawat** [comment]
and sorry to other guys who did n't get the issue menwhile you guys can explore figma designs and come up with something new or you can suggest something new by creating a new issue and describing it in detail and we will be happy to see it .

**Comment by Lakhankumawat** [comment]
I would recommend the contributor of this issue to fetch upstream and resolve conflicts before creating a new Pull Request.

**Comment by Lakhankumawat** [comment]
hi @Jagroop2000 you have 5 more days then this issue will be assigned to someone else

**Comment by nrd26** [comment]
@Lakhankumawat please let me know if there is a figma file for the required design or if I have to design it myself

**Comment by Lakhankumawat** [comment]
https://www.figma.com/file/tayD83OorLFuT62vnk401Z/Smart-Home-App-Designs-(Community)

**Comment by Lakhankumawat** [comment]
ok just wait i'll design about page

**Comment by Lakhankumawat** [comment]
So now i haven't designed the UI yet you are free to take your time no time boundations now , i'll design UI for that page

**Comment by Lakhankumawat** [comment]
https://www.figma.com/file/tayD83OorLFuT62vnk401Z/Smart-Home-App-Designs-(Community)?node-id=0%3A1
![image](https://user-images.githubusercontent.com/55774240/158319538-0bd7b1e4-b049-42c3-b12b-1826b8f057cb.png)

**Comment by Lakhankumawat** [comment]
@nrd26 you have 10 more days to make a PR for this issue , then this issue will be assigned to someone else , thanks .
