### ISSUE TITLE
Set Events Screen 

### ISSUE THREAD

**Issue by chinmayilondhe** [Lakhankumawat/smart-home-app#60]
Hey, I want to work on set Events screen as below please assign me this.

![Screenshot (60)](https://user-images.githubusercontent.com/76953832/162262624-a27bfb4d-3589-4bf4-8097-54089aeb4699.png)

**Comment by Lakhankumawat** [comment]
Duplicate https://github.com/Lakhankumawat/smart-home-app/pull/40
