### ISSUE TITLE
👤 User Profile

### ISSUE THREAD

**Issue by Lakhankumawat** [Lakhankumawat/smart-home-app#8]
![image](https://user-images.githubusercontent.com/55774240/155352815-0fbeb30e-b402-4149-80d5-da34ca39afe5.png)

**Comment by Ashish-AI** [comment]
@Lakhankumawat Assign me this as well.

**Comment by Lakhankumawat** [comment]
Sorry one person at a time  ,you can still complete first issue and then if it is. Up for grab then you'll be assigned , till then cya

**Comment by RanchoDbest** [comment]
@Lakhankumawat I am interested to work on this. Can I start woking ??

**Comment by Lakhankumawat** [comment]
Coding period for GSSOC'22 will start from 1st march , before that you can design and develop it but make sure you make your contribution after the event starts , thanks;

**Comment by Subhajitongit** [comment]
Hey I want to work on this issue, can you assign me the task?

**Comment by nrd26** [comment]
Hi,
I would love to work on bringing this beautiful UI design to life using Flutter. Please let me know if I can work on it.

**Comment by mdnazisharman2803** [comment]
Sir give me this task

**Comment by Arjun2905** [comment]
@Lakhankumawat Assign this issue to me I would like to work on this.

**Comment by Lakhankumawat** [comment]
@WarMac4964  please look into this and assign the issue to contributors .

**Comment by mdnazisharman2803** [comment]
@WarMac4964 check this issue

**Comment by Lakhankumawat** [comment]
Make sure you follow code conventions and quality of code 🙃

**Comment by Ashish-AI** [comment]
@Lakhankumawat There is some issue with the profile pic asset. After importing, we are getting a black image with the same height and width. 
cc: @WarMac4964 
Raising PR with a placeholder container.

**Comment by Lakhankumawat** [comment]
@Ashish-AI  are you still working on this issue or we assign it to someone else

**Comment by Lakhankumawat** [comment]
@Ashish-AI  will you contribute this issue or i assign it to someone else
